api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        pagination:
            enabled: false
    eager_loading:
        enabled: true
        fetch_partial: false
        max_joins: 4
        force_eager: true
